"""empty message

Revision ID: cc289e9cf9d6
Revises: 5d1d0763533f
Create Date: 2024-11-06 10:09:22.886724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc289e9cf9d6'
down_revision: Union[str, None] = '5d1d0763533f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_film_id_key', 'favorites', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('favorites_film_id_key', 'favorites', ['film_id'])
    # ### end Alembic commands ###
